config/routes.rb
Configman::Application.routes.draw do
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'user_sessions#destroy', :as => :logout

  match 'login' => 'user_sessions#new', :as => :login

  resources :user_sessions

  resources :users

   root :to => 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic

  attr_accessible :username, :email, :password, :password_confirmation
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ControllerAuthentication
  protect_from_forgery

  PER_PAGE = 15
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      redirect_to_target_or_default users_path, :notice => "Logged in successfully."
    else
      render :action => 'new'
    end
  end

  def destroy
    @user_session = UserSession.find
    @user_session.destroy
    redirect_to login_path, :notice => "You have been logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required, except: [:new, :create]

  def index
    session[:user_search] = params[:q] if !params[:q].nil? && params[:page].nil?
    session[:user_search] ||= {s: 'username'}
    @search = User.search(session[:user_search])
    @users = @search.result.paginate(page: params[:page], per_page: PER_PAGE)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    respond_to do |format|
      if @user.save
        flash[:notice] = "Thank you for signing up! You are now logged in."
        format.html { redirect_to users_path}
        format.js { render :js => "window.location = '#{users_path}'" }
      else
        format.html {  render 'new' }
        format.js { render 'error' }
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_path, notice: "Your profile has been updated." }
        format.js { render :js => "window.location = '#{users_path}'" }
      else
        format.html { render 'edit' }
        format.js { render 'error' }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user == current_user
      flash[:notice] = "Unable to delete currently logged in user"
    else
      @user.destroy
      flash[:notice] = "Successfully destroyed user."
    end
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def user_submit_label
    @user.new_record? ? "Sign up" : "Update"
  end
end

app/views/layouts/_navigation.html.erb
<nav>
  <%= link_to image_tag( 'china_historic.png', :alt => 'Dragon logo'), root_path, :class => 'brand'  %>
  <ul>
    <li>
     <%= link_to "Home", root_path %>
    </li>
    <% if logged_in? %>
      <li>
        <%= link_to 'Logout', logout_path %>
      </li>
      <li>
        <%= link_to 'Edit account', edit_user_path(current_user), class: 'dialog' %>
      </li>
    <% else %>
      <li>
        <%= link_to 'Login', login_path %>
      </li>
      <li>
        <%= link_to 'Sign up', new_user_path %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %> | Configman </title>
    <meta name="description" content="A site for keeping track of other webiste and server configurations.">
    <meta name="author" content="Railsgirl42">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container" class="container">
      <header>
        <%= render 'layouts/navigation' %>
      </header>
      <div id='main' class="main" role="main">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        <% end %>
        <%= content_tag :h2, yield(:title) if show_title? %>
        <%= yield %>
      </div>
      <footer>
        <span>&copy;2012  Railsgirl42</span>
      </footer>
    </div> <!--! end of #container -->
  </body>
</html>

app/views/user_sessions/new.html.erb
<% title "Log in" %>

<p>Don't have an account? <%= link_to "Sign up!", signup_path %></p>

<%= form_for @user_session do |f| %>
  <%= f.error_messages %>
  <table class='formTable'>
    <tr>
      <th><%= f.label :username %></th>
      <td><%= f.text_field :username, required: true %></td>
    </tr>
    <tr>
      <th><%= f.label :password %></th>
      <td><%= f.password_field :password, required: true %></td>
    </tr>
    <tr>
      <th></th>
      <td class='action_links'><%= f.submit "Log in", class: 'button' %></td>
    </tr>
  </table>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user, html: {class: 'dialog_form'}) do |f| %>
  <%= f.error_messages %>
  <table class='formTable'>
    <tr>
      <th><%= f.label :username %></th>
      <td><%= f.text_field :username%></td>
    </tr>
    <tr>
      <th><%= f.label :email, "Email Address" %></th>
      <td><%= f.email_field :email%></td>
    </tr>
    <tr>
      <th><%= f.label :password %></th>
      <td><%= f.password_field :password %></td>
    </tr>
    <tr>
      <th><%= f.label :password_confirmation, "Confirm Password" %></th>
      <td><%= f.password_field :password_confirmation %></td>
    </tr>
    <tr>
      <th></th>
      <td class='action_links'>
        <%= link_to "Cancel", root_path, class: 'button' %>
        <%= f.submit user_submit_label, class: 'button' %>
      </td>
    </tr>
  </table>
<% end %>

app/views/users/_users.html.erb
<table class="listTable sort">
  <tr>
    <th><%= sort_link @search, :username, 'Username' %></th>
    <th><%= sort_link @search, :email, 'Email' %></th>
    <th class='action'></th>
    <th class='action'> </th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
      <td class='action'><%= link_to "Edit", edit_user_path(user), class: 'icons-edit button dialog' %></td>
      <td class='action'><%= link_to "Destroy", user, data: { confirm: 'Are you sure?' }, method: :delete, class: 'icons-delete button' %></td>
    </tr>
  <% end %>
</table>
<%= will_paginate @users, :params => {} %><span class='page-info'> <%= page_entries_info @users %></span>

app/views/users/edit.html.erb
<% title "Update Profile" %>

<%= render 'form' %>

app/views/users/error.js.erb
$("#dialog_form").find('.main').html("<%= j(render(:partial => 'form')) %>");
$("#dialog_form").dialog('open');

app/views/users/index.html.erb
<% title "Users" %>

<%= search_form_for @search,  :url => users_path, :html => {:class => 'search'} do |f| %>
  <%= f.hidden_field :s, value: @search.s[0].name %>
  <%= f.label :username_cont, "Search for a user:" %>
  <%= f.text_field :username_cont, :class => 'search_field ' %>
  <%= f.submit "Search", class: "button" %>
<% end %>

<div id='users'>
  <%= render 'users'%>
</div>
<p class='action_links'><%= link_to "Add new User", new_user_path, class: 'icons-add button dialog' %></p>

<div id='dialog_form'></div>

app/views/users/index.js.erb
$("#users").html("<%= escape_javascript(render("users")) %>");
$("#q_s").val("<%= session[:user_search][:s] %>");

app/views/users/new.html.erb
<% title "Sign up" %>

<p>Already have an account? <%= link_to "Log in", login_path %>.</p>

<%= render 'form' %>